RestaurantsNearMe.MVC.Web/Models/CuisineModel.cs
namespace RestaurantsNearMe.MVC.Web.Models
{
    public class CuisineModel
    {
        public int  Id { get; set; }
        public string Name { get; set; }
    }
}

RestaurantsNearMe.MVC.Web/Models/ErrorModel.cs
namespace RestaurantsNearMe.MVC.Web.Models
{
    public class ErrorModel
    {
        public string  ErrorMessage{ get; set; }
    }
}

RestaurantsNearMe.MVC.Web/Models/RestaurantModel.cs
using System.Linq;

namespace RestaurantsNearMe.MVC.Web.Models
{
    public class RestaurantModel
    {
        public int Id { get; set; }
        public string Name  { get; set; }
        public int Rating { get; set; }
        public CuisineModel[] AvailableCuisines { get; set; }
        public string AvailableCuisineTypes { get { return string.Join(",", this.AvailableCuisines.Select(x => x.Name)); } }
    }
}

RestaurantsNearMe.MVC.Web/Models/RestaurantsViewModel.cs
using System.Collections.Generic;

namespace RestaurantsNearMe.MVC.Web.Models
{
    public class RestaurantsViewModel
    {
        public IList<RestaurantModel> AllRestaurant { get; set; }
        public bool HasError
        {
            get; set; }
        public ErrorModel Error { get; set; }
    }
}

RestaurantsNearMe.MVC.Web/Controllers/RestaurantController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using RestaurantsNearMe.Business.Services;
using RestaurantsNearMe.MVC.Web.Models;

namespace RestaurantsNearMe.MVC.Web.Controllers
{
    public class RestaurantController : AsyncController
    {
        private readonly IRestaurantService _restaurantService;

        public RestaurantController(IRestaurantService restaurantService)
        {
            _restaurantService = restaurantService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetAllAsync(string outCode)
        {
            var viewModel = new RestaurantsViewModel()
            {
                AllRestaurant = new List<RestaurantModel>(),
                Error = new ErrorModel(),
            };

            var serviceResponse = await _restaurantService.GetAllRestaurantsAsync(outCode);
            viewModel.Error.ErrorMessage = serviceResponse.ErrorResponse;
            viewModel.HasError = serviceResponse.IsError;

            if ((serviceResponse.AllRestaurants == null) ||
                (serviceResponse.AllRestaurants != null && !serviceResponse.AllRestaurants.Any()))
            {
                viewModel.HasError = true;
                viewModel.Error.ErrorMessage = "Sorry, no results found for this out code. " + viewModel.Error.ErrorMessage + " Please search again";
            }

            if (!viewModel.HasError)
                if (serviceResponse.AllRestaurants != null)
                    foreach (var rests in serviceResponse.AllRestaurants.OrderByDescending(x=>x.NumberOfRatings) )
                    {
                        viewModel.AllRestaurant.Add(new RestaurantModel(){Id=rests.Id,Name=rests.Name,Rating=rests.NumberOfRatings,
                            AvailableCuisines = rests.CuisineTypes.Select(x=> new CuisineModel {Id = x.Id, Name = x.Name}).ToArray()});
                    }

            return View("Index", viewModel);
        }
    }
}

RestaurantsNearMe.MVC.Web/Views/Restaurant/Index.cshtml
@*@using PagedList.Mvc
@model PagedList.IPagedList<RestaurantsNearMe.Business.Models.Restaurant>*@

@model RestaurantsNearMe.MVC.Web.Models.RestaurantsViewModel

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Restaurants lookup";
}

<h2>Search here </h2>

@using (Html.BeginForm("GetAll", "Restaurant", FormMethod.Get))
{
    <p>
        Search by outcode: @Html.TextBox("outCode")
        <input type="submit" value="Search" />
    </p>
}

@if (Model != null)
{
    if (Model.HasError)
    {
        <p>@Model.Error.ErrorMessage</p>
    }
else if (!Model.HasError)
{
    <p> We found @Model.AllRestaurant.Count (currently available) takeaways near you.  The highest rated are at the top</p>
        <table class="">
            <tr>
                @*<th>
                    Id
                </th>*@
                @*<th>
                    @Html.ActionLink("Name", "GetAll", new {sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter})
                </th>
                <th>
                    @Html.ActionLink("Rating", "GetAll", new {sortOrder = ViewBag.RatingSortParm, currentFilter = ViewBag.CurrentFilter})
                </th>*@
                <th>
                    Name
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Available Cuisines
                </th>
                <th></th>
            </tr>
                @foreach (var item in Model.AllRestaurant)
                {
                    <tr>
                       @Html.HiddenFor(modelItem => item.Id)

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                           @Html.DisplayFor(modelItem => item.Rating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AvailableCuisineTypes)
                        </td>
                        @*<td>
                        @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                        @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                        @Html.ActionLink("Delete", "Delete", new {id = item.Id})
                    </td>*@
                    </tr>
                }
                </table>
                <br/>

}
}

RestaurantsNearMe.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   
</head>
<body>
    @RenderBody()
</body>
</html>